// import Login from "@/components/homepage/Login";
// import SignUp from "@/components/homepage/Signup";
import { StoreProvider } from "@/redux/StoreProvider";
import "swiper/css";
import "swiper/css/bundle";
import "./globals.css";
import { Providers } from "./providers";

// import ChangePassword from "@/components/homepage/ChangePassword";
// import ForgetPassword from "@/components/homepage/ForgetPassword";
import Script from "next/script";
import React from "react";

// static
// static
// export const metadata: Metadata = {
//   title: "Myattacademy",
//   description: "Generated by create next app",
// };

// dynamic
// export async function generateMetadata({ params }: any) {
//   return {
//     title: {
//       template: "Myattacademy",
//       default: "Gateway to Excellence in Online Education and Homeschooling", // a default is required when creating a template
//     },
//     description:
//       "Explore a world of possibilities with our online homeschool programs and curriculum. We offer top-notch online education, learning platforms, and elementary to high school courses. Join our academy online for the best in virtual learning!",
//     openGraph: {
//       title: {
//         template: "Myattacademy",
//         default: "Gateway to Excellence in Online Education and Homeschooling", // a default is required when creating a template
//       },
//       description:
//         "Explore a world of possibilities with our online homeschool programs and curriculum. We offer top-notch online education, learning platforms, and elementary to high school courses. Join our academy online for the best in virtual learning!",
//       url: process.env.DOMAIN,
//       siteName: "Myattacademy",
//       // images: [
//       //   {
//       //     url: "https://nextjs.org/og.png",
//       //     width: 800,
//       //     height: 600,
//       //   },
//       //   {
//       //     url: "https://nextjs.org/og-alt.png",
//       //     width: 1800,
//       //     height: 1600,
//       //     alt: "My custom alt",
//       //   },
//       // ],
//       // locale: "en_US",
//       type: "website",
//       // robots: {
//       //   index: false,
//       //   follow: true,
//       //   nocache: true,
//       //   googleBot: {
//       //     index: true,
//       //     follow: false,
//       //     noimageindex: true,
//       //     "max-video-preview": -1,
//       //     "max-image-preview": "large",
//       //     "max-snippet": -1,
//       //   },
//       // },
//     },
//     twitter: {
//       card: "summary_large_image", // card
//       title: "Myattacademy",
//       description:
//         "Explore a world of possibilities with our online homeschool programs and curriculum. We offer top-notch online education, learning platforms, and elementary to high school courses. Join our academy online for the best in virtual learning!",
//       // siteId: "1467726470533754880",
//       creator: "Myattacademy",
//       // creatorId: "1467726470533754880",
//       // images: {
//       //   url: "https://nextjs.org/og.png",
//       //   alt: "Next.js Logo",
//       // },
//       // app: {
//       //   name: "twitter_app",
//       //   id: {
//       //     iphone: "twitter_app://iphone",
//       //     ipad: "twitter_app://ipad",
//       //     googleplay: "twitter_app://googleplay",
//       //   },
//       //   url: {
//       //     iphone: "https://iphone_url",
//       //     ipad: "https://ipad_url",
//       //   },
//       // },
//     },
//   };
// }

// const GOOGLE_TAG_ID = process.env.NEXT_PUBLIC_GOOGLE_TAG_ID;
// const GOOGLE_TAG_ID = "g2O-Ul0aYjkYbELS9lutNfEgu17AUXaPTGbYkXVj2o0";
const GOOGLE_TAG_ID = "G-B8HCKJXJWW";
// console.table({ GOOGLE_TAG_ID });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Other head elements */}
        <meta
          name="google-site-verification"
          content="WmfebgIgZysd4k4gKSEVpgAHNDTvDtghE_JUgDcpKSs"
        />
        {/* FAVICONS */}
        <link
          rel="icon"
          href="favicon.png"
          // href="https://admin.myattacademy.com/frontend/assets/img/favicon-16x16.png"
          type="image/png"
          sizes="16x16"
        />
        <link
          rel="shortcut icon"
          href="favicon.png"
          // href="https://admin.myattacademy.com/frontend/assets/img/favicon-16x16.png"
          type="image/x-icon"
        />
        <link
          rel="shortcut icon"
          href="favicon.png"
          // href="https://admin.myattacademy.com/frontend/assets/img/favicon.png"
        />

        <link
          rel="apple-touch-icon-precomposed"
          type="image/x-icon"
          // href="favicon.png"
          href="https://admin.myattacademy.com/frontend/assets/img/apple-icon-72x72.png"
          sizes="72x72"
        />
        <link
          rel="apple-touch-icon-precomposed"
          type="image/x-icon"
          // href="favicon.png"
          href="https://admin.myattacademy.com/frontend/assets/img/apple-icon-114x114.png"
          sizes="114x114"
        />
        <link
          rel="apple-touch-icon-precomposed"
          type="image/x-icon"
          // href="favicon.png"
          href="https://admin.myattacademy.com/frontend/assets/img/apple-icon-144x144.png"
          sizes="144x144"
        />
        <link
          rel="apple-touch-icon-precomposed"
          type="image/x-icon"
          // href="favicon.png"
          href="https://admin.myattacademy.com/frontend/assets/img/favicon-16x16.png"
        />
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GOOGLE_TAG_ID}`}
        />
        <Script id="google-analytics">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','${GOOGLE_TAG_ID}')
          `}
        </Script>
      </head>
      <body>
        {/* facebook chat start */}
        <>
          <div id="fb-root"></div>
          <div id="fb-customer-chat" className="fb-customerchat"></div>

          <Script id="facebookChat">
            {`
              var chatbox = document.getElementById('fb-customer-chat');
              chatbox.setAttribute("page_id", "185738294615806");
              chatbox.setAttribute("attribution", "biz_inbox");
            `}
          </Script>

          <Script id="facebookChatInit">
            {`
              window.fbAsyncInit = function() {
                FB.init({
                  xfbml            : true,
                  version          : 'v18.0'
                });
              };

              (function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
                fjs.parentNode.insertBefore(js, fjs);
              }(document, 'script', 'facebook-jssdk'));
            `}
          </Script>
        </>
        {/* facebook chat end */}
        <StoreProvider>
          <Providers>
            {children}
            {/* <Login /> */}
            {/* <SignUp /> */}
            {/* <ForgetPassword /> */}
            {/* <ChangePassword /> */}
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
